

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using OracleDataMoverEF.Repositories;
using OracleDataMoverEF.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OracleDataMoverEF.UnitOfWork
{
    
    public interface IUnitOfWork : IDisposable
    {
    
    	bool UserHasPermission { get; }
    
    
    	DATABASE_INFORepository DATABASE_INFORepository { get; }
    	ODMSettingRepository ODMSettingRepository { get; }
    	OraUtilityRepository OraUtilityRepository { get; }
    	PARMRepository PARMRepository { get; }
    	RemapFunctionRepository RemapFunctionRepository { get; }
    	TemplateRepository TemplateRepository { get; }
    	TemplateJobHistoryRepository TemplateJobHistoryRepository { get; }
    	TemplateParmRepository TemplateParmRepository { get; }
    	TemplateSchemaRepository TemplateSchemaRepository { get; }
    	TemplateSchemaRemapRepository TemplateSchemaRemapRepository { get; }
    	TemplateSchemaSanitizeRepository TemplateSchemaSanitizeRepository { get; }
    	TemplateSchemaTableRepository TemplateSchemaTableRepository { get; }
    	
    	
    
        void Save();
        ODMEntities ReturnContext();
        bool RunFgacPermission(string networkUserName, int fgacId);
        int RunRolePermission(string role);
    	void InitializeTransaction();
    }
    
}










