

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//using Oracle.DataAccess.Client;
using Oracle.ManagedDataAccess.Client;
using System;
using System.Data;
using System.Data.Common;
using System.Data.Entity;
using System.Linq;
using System.Security.Principal;
using System.Configuration;
using System.Data.Entity.Infrastructure;
using log4net;
using Eca.Common;
using OracleDataMoverEF.Repositories;
using OracleDataMoverEF.EF;

namespace OracleDataMoverEF.UnitOfWork
{
    
    public partial class ODMDataContext : DataContext<IODMEntities>
    {
    
    	private static ILog logger = log4net.LogManager.GetLogger(typeof(ODMDataContext));
        private bool disposed = false;
    	private readonly ODMEntities context = null;
    	private int _currentFgac { get; set; }
    
    		public ODMDataContext()
    		{
    			this._currentFgac = 0;
    		}
    
            public ODMDataContext(IODMEntities context, string name)
                    : base(context, name)
            {
    		    this.context = (ODMEntities)context;
            }
    
        public bool HasChanges()
        {
            return ((ODMEntities)this.context).ObjectChanges();
        }
    
    	private DATABASE_INFORepository dATABASE_INFORepository;
    	private ODMSettingRepository oDMSettingRepository;
    	private OraUtilityRepository oraUtilityRepository;
    	private PARMRepository pARMRepository;
    	private RemapFunctionRepository remapFunctionRepository;
    	private TemplateRepository templateRepository;
    	private TemplateJobHistoryRepository templateJobHistoryRepository;
    	private TemplateParmRepository templateParmRepository;
    	private TemplateSchemaRepository templateSchemaRepository;
    	private TemplateSchemaRemapRepository templateSchemaRemapRepository;
    	private TemplateSchemaSanitizeRepository templateSchemaSanitizeRepository;
    	private TemplateSchemaTableRepository templateSchemaTableRepository;
    	public virtual DATABASE_INFORepository DATABASE_INFORepository
    	{
    		get 
    		{
    			if (this.dATABASE_INFORepository == null)
    			{
    				this.dATABASE_INFORepository = new DATABASE_INFORepository(this);
    			}
    
    			return this.dATABASE_INFORepository;
    		}
    	}
    
    	public virtual ODMSettingRepository ODMSettingRepository
    	{
    		get 
    		{
    			if (this.oDMSettingRepository == null)
    			{
    				this.oDMSettingRepository = new ODMSettingRepository(this);
    			}
    
    			return this.oDMSettingRepository;
    		}
    	}
    
    	public virtual OraUtilityRepository OraUtilityRepository
    	{
    		get 
    		{
    			if (this.oraUtilityRepository == null)
    			{
    				this.oraUtilityRepository = new OraUtilityRepository(this);
    			}
    
    			return this.oraUtilityRepository;
    		}
    	}
    
    	public virtual PARMRepository PARMRepository
    	{
    		get 
    		{
    			if (this.pARMRepository == null)
    			{
    				this.pARMRepository = new PARMRepository(this);
    			}
    
    			return this.pARMRepository;
    		}
    	}
    
    	public virtual RemapFunctionRepository RemapFunctionRepository
    	{
    		get 
    		{
    			if (this.remapFunctionRepository == null)
    			{
    				this.remapFunctionRepository = new RemapFunctionRepository(this);
    			}
    
    			return this.remapFunctionRepository;
    		}
    	}
    
    	public virtual TemplateRepository TemplateRepository
    	{
    		get 
    		{
    			if (this.templateRepository == null)
    			{
    				this.templateRepository = new TemplateRepository(this);
    			}
    
    			return this.templateRepository;
    		}
    	}
    
    	public virtual TemplateJobHistoryRepository TemplateJobHistoryRepository
    	{
    		get 
    		{
    			if (this.templateJobHistoryRepository == null)
    			{
    				this.templateJobHistoryRepository = new TemplateJobHistoryRepository(this);
    			}
    
    			return this.templateJobHistoryRepository;
    		}
    	}
    
    	public virtual TemplateParmRepository TemplateParmRepository
    	{
    		get 
    		{
    			if (this.templateParmRepository == null)
    			{
    				this.templateParmRepository = new TemplateParmRepository(this);
    			}
    
    			return this.templateParmRepository;
    		}
    	}
    
    	public virtual TemplateSchemaRepository TemplateSchemaRepository
    	{
    		get 
    		{
    			if (this.templateSchemaRepository == null)
    			{
    				this.templateSchemaRepository = new TemplateSchemaRepository(this);
    			}
    
    			return this.templateSchemaRepository;
    		}
    	}
    
    	public virtual TemplateSchemaRemapRepository TemplateSchemaRemapRepository
    	{
    		get 
    		{
    			if (this.templateSchemaRemapRepository == null)
    			{
    				this.templateSchemaRemapRepository = new TemplateSchemaRemapRepository(this);
    			}
    
    			return this.templateSchemaRemapRepository;
    		}
    	}
    
    	public virtual TemplateSchemaSanitizeRepository TemplateSchemaSanitizeRepository
    	{
    		get 
    		{
    			if (this.templateSchemaSanitizeRepository == null)
    			{
    				this.templateSchemaSanitizeRepository = new TemplateSchemaSanitizeRepository(this);
    			}
    
    			return this.templateSchemaSanitizeRepository;
    		}
    	}
    
    	public virtual TemplateSchemaTableRepository TemplateSchemaTableRepository
    	{
    		get 
    		{
    			if (this.templateSchemaTableRepository == null)
    			{
    				this.templateSchemaTableRepository = new TemplateSchemaTableRepository(this);
    			}
    
    			return this.templateSchemaTableRepository;
    		}
    	}
    
    }
    
}










