//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleDataMoverOraEF.EF
{
    using System;
    using System.Collections.Generic;
    using Eca.Common;
    
    public partial class ALL_CONSTRAINTS : Entity
    {
        public string OWNER { get; set; }
        public string CONSTRAINT_NAME { get; set; }
        public string CONSTRAINT_TYPE { get; set; }
        public string TABLE_NAME { get; set; }
        public string SEARCH_CONDITION { get; set; }
        public string SEARCH_CONDITION_VC { get; set; }
        public string R_OWNER { get; set; }
        public string R_CONSTRAINT_NAME { get; set; }
        public string DELETE_RULE { get; set; }
        public string STATUS { get; set; }
        public string DEFERRABLE { get; set; }
        public string DEFERRED { get; set; }
        public string VALIDATED { get; set; }
        public string GENERATED { get; set; }
        public string BAD { get; set; }
        public string RELY { get; set; }
        public Nullable<System.DateTime> LAST_CHANGE { get; set; }
        public string INDEX_OWNER { get; set; }
        public string INDEX_NAME { get; set; }
        public string INVALID { get; set; }
        public string VIEW_RELATED { get; set; }
        public Nullable<decimal> ORIGIN_CON_ID { get; set; }
    }
}
