//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleDataMoverOraEF.EF
{
    using System;
    using System.Collections.Generic;
    using Eca.Common;
    
    public partial class ALL_USERS : Entity
    {
        public string USERNAME { get; set; }
        public decimal USER_ID { get; set; }
        public System.DateTime CREATED { get; set; }
        public string COMMON { get; set; }
        public string ORACLE_MAINTAINED { get; set; }
        public string INHERITED { get; set; }
        public string DEFAULT_COLLATION { get; set; }
        public string IMPLICIT { get; set; }
        public string ALL_SHARD { get; set; }
    }
}
