//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleDataMoverOraEF.EF
{
    using System;
    using System.Collections.Generic;
    using Eca.Common;
    
    public partial class DBA_DATAPUMP_JOBS : Entity
    {
        public string OWNER_NAME { get; set; }
        public string JOB_NAME { get; set; }
        public string OPERATION { get; set; }
        public string JOB_MODE { get; set; }
        public string STATE { get; set; }
        public decimal DEGREE { get; set; }
        public decimal ATTACHED_SESSIONS { get; set; }
        public decimal DATAPUMP_SESSIONS { get; set; }
    }
}
