

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//using Oracle.DataAccess.Client;
using Oracle.ManagedDataAccess.Client;
using System;
using System.Data;
using System.Data.Common;
using System.Data.Entity;
using System.Linq;
using System.Security.Principal;
using System.Configuration;
using System.Data.Entity.Infrastructure;
using log4net;
using Eca.Common;
using OracleDataMoverOraEF.Repositories;
using OracleDataMoverOraEF.EF;

namespace OracleDataMoverOraEF.UnitOfWork
{
    
    public partial class OraDataContext : DataContext<IOraEntities>
    {
    
    	private static ILog logger = log4net.LogManager.GetLogger(typeof(OraDataContext));
        private bool disposed = false;
    	private readonly OraEntities context = null;
    	private int _currentFgac { get; set; }
    
    		public OraDataContext()
    		{
    			this._currentFgac = 0;
    		}
    
            public OraDataContext(IOraEntities context, string name)
                    : base(context, name)
            {
    		    this.context = (OraEntities)context;
            }
    
    	private ALL_CONS_COLUMNSRepository aLL_CONS_COLUMNSRepository;
    	private ALL_CONSTRAINTSRepository aLL_CONSTRAINTSRepository;
    	private ALL_TAB_COLSRepository aLL_TAB_COLSRepository;
    	private ALL_TABLESRepository aLL_TABLESRepository;
    	private ALL_USERSRepository aLL_USERSRepository;
    	public virtual ALL_CONS_COLUMNSRepository ALL_CONS_COLUMNSRepository
    	{
    		get 
    		{
    			if (this.aLL_CONS_COLUMNSRepository == null)
    			{
    				this.aLL_CONS_COLUMNSRepository = new ALL_CONS_COLUMNSRepository(this);
    			}
    
    			return this.aLL_CONS_COLUMNSRepository;
    		}
    	}
    
    	public virtual ALL_CONSTRAINTSRepository ALL_CONSTRAINTSRepository
    	{
    		get 
    		{
    			if (this.aLL_CONSTRAINTSRepository == null)
    			{
    				this.aLL_CONSTRAINTSRepository = new ALL_CONSTRAINTSRepository(this);
    			}
    
    			return this.aLL_CONSTRAINTSRepository;
    		}
    	}
    
    	public virtual ALL_TAB_COLSRepository ALL_TAB_COLSRepository
    	{
    		get 
    		{
    			if (this.aLL_TAB_COLSRepository == null)
    			{
    				this.aLL_TAB_COLSRepository = new ALL_TAB_COLSRepository(this);
    			}
    
    			return this.aLL_TAB_COLSRepository;
    		}
    	}
    
    	public virtual ALL_TABLESRepository ALL_TABLESRepository
    	{
    		get 
    		{
    			if (this.aLL_TABLESRepository == null)
    			{
    				this.aLL_TABLESRepository = new ALL_TABLESRepository(this);
    			}
    
    			return this.aLL_TABLESRepository;
    		}
    	}
    
    	public virtual ALL_USERSRepository ALL_USERSRepository
    	{
    		get 
    		{
    			if (this.aLL_USERSRepository == null)
    			{
    				this.aLL_USERSRepository = new ALL_USERSRepository(this);
    			}
    
    			return this.aLL_USERSRepository;
    		}
    	}
    
    }
    
}










