//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleDataMoverEF.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Core.Objects.DataClasses;
    using System.Linq;
    using Eca.Common;
    
    
    public interface IODMEntities : IDbContext
    {
        string LoggedInUserId { get; set; }
        DbChangeTracker ChangeTracker { get; }
        int SaveChanges();
        IDbSet<TEntity> GetSet<TEntity>() where TEntity : class;
        IDbSet<Template> Templates1 { get; set; }
        IDbSet<PARM> PARMs { get; set; }
        IDbSet<DATABASE_INFO> DATABASE_INFO { get; set; }
        IDbSet<RemapFunction> RemapFunctions { get; set; }
        IDbSet<TemplateSchema> TemplateSchemas { get; set; }
        IDbSet<TemplateSchemaTable> TemplateSchemaTables { get; set; }
        IDbSet<TemplateSchemaSanitize> TemplateSchemaSanitizes { get; set; }
        IDbSet<TemplateParm> TemplateParms { get; set; }
        IDbSet<ODMSetting> ODMSettings { get; set; }
        IDbSet<OraUtility> OraUtilities { get; set; }
        IDbSet<TemplateSchemaRemap> TemplateSchemaRemaps { get; set; }
        IDbSet<TemplateJobHistory> TemplateJobHistories { get; set; }
    }
}
