//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleDataMoverEF.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ODMEntities : DbContext, IODMEntities
    {
    public ODMEntities(string ConnStringName)
           //: base("name=" + ConnStringName)
            : base(ConnStringName)
        {


        }
    
        public ODMEntities()
            : base("name=ODMEntities")
        {
           // this.Configuration.LazyLoadingEnabled = false;
        }



        public IDbSet<TEntity> GetSet<TEntity>() where TEntity : class 
        {
            return this.Set<TEntity>();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public IDbSet<Template> Templates1 { get; set; }
        public IDbSet<PARM> PARMs { get; set; }
        public IDbSet<DATABASE_INFO> DATABASE_INFO { get; set; }
        public IDbSet<RemapFunction> RemapFunctions { get; set; }
        public IDbSet<TemplateSchema> TemplateSchemas { get; set; }
        public IDbSet<TemplateSchemaTable> TemplateSchemaTables { get; set; }
        public IDbSet<TemplateSchemaSanitize> TemplateSchemaSanitizes { get; set; }
        public IDbSet<TemplateParm> TemplateParms { get; set; }
        public IDbSet<ODMSetting> ODMSettings { get; set; }
        public IDbSet<OraUtility> OraUtilities { get; set; }
        public IDbSet<TemplateSchemaRemap> TemplateSchemaRemaps { get; set; }
        public IDbSet<TemplateJobHistory> TemplateJobHistories { get; set; }
    }
}
