//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleDataMoverEF.EF
{
    using System;
    using System.Collections.Generic;
    using Eca.Common;
    using System.Text.RegularExpressions;
    
    public partial class RemapFunction : Entity
    {
        public RemapFunction()
        {
            this.TEMPLATE_SCHEMA_SANITIZE = new HashSet<TemplateSchemaSanitize>();
        }
    
        public string SchemaName { get; set; }
        public string PackageName { get; set; }
        public string FunctionName { get; set; }
    
        public virtual ICollection<TemplateSchemaSanitize> TEMPLATE_SCHEMA_SANITIZE { get; set; }
    }
}
