//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleDataMoverEF.EF
{
    using System;
    using System.Collections.Generic;
    using Eca.Common;
    using System.Text.RegularExpressions;
    
    public partial class TemplateSchema : Entity
    {
        public TemplateSchema()
        {
            this.TEMPLATE_SCHEMA_TABLE = new HashSet<TemplateSchemaTable>();
            this.TEMPLATE_SCHEMA_SANITIZE = new HashSet<TemplateSchemaSanitize>();
        }
    
        public string TemplateId { get; set; }
        public string SchemaName { get; set; }
    
        public virtual Template TEMPLATE { get; set; }
        public virtual ICollection<TemplateSchemaTable> TEMPLATE_SCHEMA_TABLE { get; set; }
        public virtual ICollection<TemplateSchemaSanitize> TEMPLATE_SCHEMA_SANITIZE { get; set; }
    }
}
