//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OracleDataMoverEF.EF
{
    using System;
    using System.Collections.Generic;
    using Eca.Common;
    using System.Text.RegularExpressions;
    
    public partial class Template : Entity
    {
        public Template()
        {
            this.TEMPLATE_SCHEMA = new HashSet<TemplateSchema>();
            this.TEMPLATE_PARM = new HashSet<TemplateParm>();
            this.TEMPLATE_SCHEMA_REMAP = new HashSet<TemplateSchemaRemap>();
            this.TEMPLATE_JOB_HISTORY = new HashSet<TemplateJobHistory>();
        }
    
        public string Name { get; set; }
        public string DATABASE_ID { get; set; }
        public string PARFileName { get; set; }
        public string BATFileName { get; set; }
        public string ORA_UTILITY_ID { get; set; }
        public string DMPFileName { get; set; }
        public string UtilJobname { get; set; }
    
        public virtual DATABASE_INFO DATABASE_INFO { get; set; }
        public virtual ICollection<TemplateSchema> TEMPLATE_SCHEMA { get; set; }
        public virtual ICollection<TemplateParm> TEMPLATE_PARM { get; set; }
        public virtual OraUtility ORA_UTILITY { get; set; }
        public virtual ICollection<TemplateSchemaRemap> TEMPLATE_SCHEMA_REMAP { get; set; }
        public virtual ICollection<TemplateJobHistory> TEMPLATE_JOB_HISTORY { get; set; }
    }
}
